version: '3.4'

services:
  app1:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    
  app2:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile

  db:
    image: postgres
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - local_pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 79ostap@ukr.net
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - pgadmin-data:/var/lib/pgadmin



networks:
  mynetwork:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data:
